// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8C58tBIbFHjSl4vGC_BBkbRaaVgMA0KA',
    appId: '1:317841869544:android:025d012f101691069fd75d',
    messagingSenderId: '317841869544',
    projectId: 'smart-notes-abdy',
    storageBucket: 'smart-notes-abdy.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSQ-HmWzqYypECBOowzlacCKp7DkhNgk',
    appId: '1:317841869544:web:9731868e726a56869fd75d',
    messagingSenderId: '317841869544',
    projectId: 'smart-notes-abdy',
    authDomain: 'smart-notes-abdy.firebaseapp.com',
    storageBucket: 'smart-notes-abdy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Xp-D_gfCTrW8bg11Hz9K3ebgo086kHg',
    appId: '1:317841869544:ios:f26435a751b436079fd75d',
    messagingSenderId: '317841869544',
    projectId: 'smart-notes-abdy',
    storageBucket: 'smart-notes-abdy.firebasestorage.app',
    iosBundleId: 'com.example.smartNotes',
  );

}