platform :ios, '13.0'

# Cette ligne est cruciale pour que Flutter fonctionne
require_relative '../.flutter-plugins-dependencies'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Configuration standard de Flutter
  flutter_root = File.expand_path('..', File.dirname(File.realpath(__FILE__)))
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'xcode_backend.dart')
  
  # On garde ta ligne mais elle a besoin du contexte Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
